### PR TITLE
Improved using-permissions table of contents

### PR DESCRIPTION
**Pull request by Calytic**
Additional edits

### CODE REVIEW

**Comment by lukespragg** [comment]
Why the change from player to user? We generally stick to "player" in the documentation and descriptions.

**Comment by Calytic** [comment]
It's inconsistent, some say player, some say user.  I can change it back to player but it ought to be one or the other

**Comment by Calytic** [comment]
Also the umod command is "user"
Like umod.grant user Wulf umod.reload

**Comment by lukespragg** [comment]
"player" is generally what we've been using and moving to.

**Comment by Calytic** [comment]
We intend to change "user" to "player" in umod.grant like commands as well then?

**Comment by lukespragg** [comment]
That's the idea, yes.

**Pull request merged**
